services:
  - type: web
    name: auto-school-fastapi
    env: python
    buildCommand: ""
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
    plan: free
